version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "rootPwd"
    networks:
      - rabbit-net
  info:
    build: .
    ports:
      - "3000:3000"
    networks:
      - rabbit-net
networks:
  rabbit-net:
    driver: bridge
